# f = open("rehan.txt", "w")
# f.write("rehan is a gud bot")
# f.close()
# f = open("rehan2.txt","a")
# f.write("how are you doing? \n")
# f.close()
f = open("rehan2.txt","r+")
print(f.read())
#f.write("whats up ?")