mystr = "Rehan is a good man"
print(len(mystr))
print(mystr[0:5])
print(mystr[::-1])
print(mystr[11:-4])
print(mystr.isalnum())
print(mystr.endswith("man"))
print(mystr.endswith("manw"))
print(mystr.capitalize())
print(mystr.upper())
print(mystr.lower())
print(mystr.replace("Rehan", "Reho"))
print(mystr.count("n"))
